"""add interview type to candidates

Revision ID: 67c1fface56f
Revises: dcab4c787d45
Create Date: 2026-09-23 13:50:51.358910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "67c1fface56f"
down_revision: Union[str, Sequence[str], None] = "dcab4c787d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidates", sa.Column("interview_type", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "candidates", "resume_text", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_index(op.f("ix_candidates_name"), table_name="candidates")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_candidates_name"), "candidates", ["name"], unique=False)
    op.alter_column("candidates", "resume_text", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("candidates", "interview_type")
    # ### end Alembic commands ###
