"""add configuration columns to interviews/ relationship to candidate

Revision ID: 7968ccf8ffb4
Revises: 0a3db6382224
Create Date: 2026-09-30 10:45:37.140491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7968ccf8ffb4'
down_revision: Union[str, Sequence[str], None] = '0a3db6382224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('difficulty', sa.String(length=10), server_default='MEDIUM', nullable=False))
    op.add_column('interviews', sa.Column('question_count', sa.Integer(), server_default='10', nullable=False))
    op.add_column('interviews', sa.Column('use_skills', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('interviews', sa.Column('use_projects', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('interviews', sa.Column('use_experience', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('interviews', sa.Column('use_resume', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'use_resume')
    op.drop_column('interviews', 'use_experience')
    op.drop_column('interviews', 'use_projects')
    op.drop_column('interviews', 'use_skills')
    op.drop_column('interviews', 'question_count')
    op.drop_column('interviews', 'difficulty')
    # ### end Alembic commands ###
